/*
 * linux/include/asm-arm/arch-s5h2150/gpio.h
 *
 *  Copyright (C) 2003-2007 Samsung Electronics
 *  Author: ij.jang@samsung.com
 *
 */

#ifndef _S5H2150_GPIO_H_
#define _S5H2150_GPIO_H_

/*-----------------------------------------------------*/
/* GPIO ports */
#define V_GPIO_PORT(offset)  (*(volatile unsigned *)(V_GPIO_BASE+(offset)))

#define O_GPIOSELA		(0x00)
#define O_GPIOSELB		(0x04)
#define O_GPIOSELC		(0x08)

#define O_GPIOA_DAT		(0x0C)
#define O_GPIOA_IOCON		(0x10)
#define O_GPIOA_PUPCON		(0x14)

#define O_GPIOB_DAT		(0x18)
#define O_GPIOB_IOCON		(0x1C)
#define O_GPIOB_PUPCON		(0x20)

#define O_GPIOC_DAT		(0x24)
#define O_GPIOC_IOCON		(0x28)
#define O_GPIOC_PUPCON		(0x2C)

#define O_GPIOD_DAT		(0x30)
#define O_GPIOD_IOCON		(0x34)
#define O_GPIOD_PUPCON		(0x38)

#define O_GPIOE_DAT		(0x3C)
#define O_GPIOE_IOCON		(0x40)
#define O_GPIOE_PUPCON		(0x44)

#define O_GPIOF_DAT		(0x48)
#define O_GPIOF_IOCON		(0x4C)
#define O_GPIOF_PUPCON		(0x50)

#define O_GPIOG_DAT		(0x54)
#define O_GPIOG_IOCON		(0x58)
#define O_GPIOG_PUPCON		(0x5C)

#define O_GPIOH_DAT		(0x60)
#define O_GPIOH_IOCON		(0x64)
#define O_GPIOH_PUPCON		(0x68)

#define O_GPIO_DAT		(0x6C)
#define O_GPIO_IOCON		(0x70)
#define O_GPIO_PUPCON		(0x74)

#define O_EXTINTRCON		(0x78)
#define O_PINSELCON		(0x7C)

/* for C */
#define R_GPIOSELA		V_GPIO_PORT(O_GPIOSELA)
#define R_GPIOSELB		V_GPIO_PORT(O_GPIOSELB)
#define R_GPIOSELC		V_GPIO_PORT(O_GPIOSELC)

#define R_GPIOA_DAT		V_GPIO_PORT(O_GPIOA_DAT)
#define R_GPIOA_IOCON		V_GPIO_PORT(O_GPIOA_IOCON)
#define R_GPIOA_PUPCON		V_GPIO_PORT(O_GPIOA_PUPCON)

#define R_GPIOB_DAT		V_GPIO_PORT(O_GPIOB_DAT)
#define R_GPIOB_IOCON		V_GPIO_PORT(O_GPIOB_IOCON)
#define R_GPIOB_PUPCON		V_GPIO_PORT(O_GPIOB_PUPCON)

#define R_GPIOC_DAT		V_GPIO_PORT(O_GPIOC_DAT)
#define R_GPIOC_IOCON		V_GPIO_PORT(O_GPIOC_IOCON)
#define R_GPIOC_PUPCON		V_GPIO_PORT(O_GPIOC_PUPCON)

#define R_GPIOD_DAT		V_GPIO_PORT(O_GPIOD_DAT)
#define R_GPIOD_IOCON		V_GPIO_PORT(O_GPIOD_IOCON)
#define R_GPIOD_PUPCON		V_GPIO_PORT(O_GPIOD_PUPCON)

#define R_GPIOE_DAT		V_GPIO_PORT(O_GPIOE_DAT)
#define R_GPIOE_IOCON		V_GPIO_PORT(O_GPIOE_IOCON)
#define R_GPIOE_PUPCON		V_GPIO_PORT(O_GPIOE_PUPCON)

#define R_GPIOF_DAT		V_GPIO_PORT(O_GPIOF_DAT)
#define R_GPIOF_IOCON		V_GPIO_PORT(O_GPIOF_IOCON)
#define R_GPIOF_PUPCON		V_GPIO_PORT(O_GPIOF_PUPCON)

#define R_GPIOG_DAT		V_GPIO_PORT(O_GPIOG_DAT)
#define R_GPIOG_IOCON		V_GPIO_PORT(O_GPIOG_IOCON)
#define R_GPIOG_PUPCON		V_GPIO_PORT(O_GPIOG_PUPCON)

#define R_GPIOH_DAT		V_GPIO_PORT(O_GPIOH_DAT)
#define R_GPIOH_IOCON		V_GPIO_PORT(O_GPIOH_IOCON)
#define R_GPIOH_PUPCON		V_GPIO_PORT(O_GPIOH_PUPCON)

#define R_GPIO_DAT		V_GPIO_PORT(O_GPIV_GPIO_PORT(O_DAT)
#define R_GPIO_IOCON		V_GPIO_PORT(O_GPIV_GPIO_PORT(O_IOCON)
#define R_GPIO_PUPCON		V_GPIO_PORT(O_GPIV_GPIO_PORT(O_PUPCON)

#define R_EXTINTRCON		V_GPIO_PORT(O_EXTINTRCON)
#define R_PINSELCON		V_GPIO_PORT(O_PINSELCON)

#endif
