#!/bin/sh
#
# © Copyright 1996-2010, ZsoltTech.Com
#       by Ser Lev Arris <arris@ZsoltTech.Com>
#
#       donated for the SamyGo Project
#       http://samygo.sourceforge.net/
#
#       Version: SamyGO svn $Id$

. /dtv/SGO.env

case $1 in 
	start)
	mknod /dev/sam/fb0 c 29 0
	# for systems with modular fb kernel support
	# base: /lib/modules/2.6.18_SELP-ARM/kernel/drivers/video/
	# TODO: fbcon
	# cseries, mod order correct?
	insmod $MOD_DIR/kernel/drivers/video/fb.ko
	
	insmod $MOD_DIR/kernel/drivers/video/fb_sys_fops.ko
	insmod $MOD_DIR/kernel/drivers/video/syscopyarea.ko
	insmod $MOD_DIR/kernel/drivers/video/sysfillrect.ko
	insmod $MOD_DIR/kernel/drivers/video/sysimgblt.ko

	insmod $MOD_DIR/kernel/drivers/video/cfbcopyarea.ko
	insmod $MOD_DIR/kernel/drivers/video/cfbfillrect.ko
	insmod $MOD_DIR/kernel/drivers/video/cfbimgblt.ko

	insmod $MOD_DIR/kernel/drivers/video/vfb.ko vfb_enable=1 videomemorysize=2073600
	;;
	stop)
	;;
	status)
	cat /proc/fb
	;;
	*)
	echo "Usage: $0 {start|stop|status}" 1>&2
	exit 0
	;;
esac
