diff -ur old/Makefile new/Makefile
--- old/Makefile	2006-03-15 22:36:20.000000000 +0100
+++ new/Makefile	2010-02-03 13:18:47.000000000 +0100
@@ -1,19 +1,23 @@
 INCLUDEDIR = .
 
-CFLAGS := -I$(INCLUDEDIR) -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -O2
+LOCAL_CFLAGS := -I$(INCLUDEDIR) -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE
 
 all: mksquashfs unsquashfs
 
 mksquashfs: mksquashfs.o read_fs.o sort.o
-	$(CC) mksquashfs.o read_fs.o sort.o -lz -o $@
+	$(CC) $(LDFLAGS) mksquashfs.o read_fs.o sort.o -lz -o $@
 
 mksquashfs.o: mksquashfs.c squashfs_fs.h mksquashfs.h global.h sort.h
+	$(CC) $(CFLAGS) $(LOCAL_CFLAGS) -c -o mksquashfs.o mksquashfs.c
 
 read_fs.o: read_fs.c squashfs_fs.h read_fs.h global.h
+	$(CC) $(CFLAGS) $(LOCAL_CFLAGS) -c -o read_fs.o read_fs.c
 
 sort.o: sort.c squashfs_fs.h global.h sort.h
+	$(CC) $(CFLAGS) $(LOCAL_CFLAGS) -c -o sort.o sort.c
 
 unsquashfs: unsquashfs.o
-	$(CC) unsquashfs.o -lz -o $@
+	$(CC) $(LDFLAGS) unsquashfs.o -lz -o $@
 
 unsquashfs.o: unsquashfs.c squashfs_fs.h read_fs.h global.h
+	$(CC) $(CFLAGS) $(LOCAL_CFLAGS) -c -o unsquashfs.o unsquashfs.c
